### ISSUE TITLE
fails to build with poco >= 1.12

### ISSUE THREAD

**Issue by ra1nb0w** [pothosware/PothosCore#241]
This is the error:
```
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_science_PothosCore/PothosCore/work/PothosCore-0.7.1/lib/System/Logger.cpp:140:35: error: no matching constructor for initialization of 'Poco::Net::DatagramSocket'
        Poco::Net::DatagramSocket sock(Poco::Net::SocketAddress(addr, 0));
                                  ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/Poco/Net/DatagramSocket.h:45:11: note: candidate constructor not viable: no known conversion from 'Poco::Net::SocketAddress' to 'SocketAddress::Family' (aka 'Poco::Net::AddressFamily::Family') for 1st argument
        explicit DatagramSocket(SocketAddress::Family family);
                 ^
/opt/local/include/Poco/Net/DatagramSocket.h:60:2: note: candidate constructor not viable: no known conversion from 'Poco::Net::SocketAddress' to 'const Poco::Net::Socket' for 1st argument
        DatagramSocket(const Socket& socket);
        ^
/opt/local/include/Poco/Net/DatagramSocket.h:66:2: note: candidate constructor not viable: no known conversion from 'Poco::Net::SocketAddress' to 'const Poco::Net::DatagramSocket' for 1st argument
        DatagramSocket(const DatagramSocket& socket);
        ^
/opt/local/include/Poco/Net/DatagramSocket.h:283:2: note: candidate constructor not viable: no known conversion from 'Poco::Net::SocketAddress' to 'Poco::Net::SocketImpl *' for 1st argument
        DatagramSocket(SocketImpl* pImpl);
        ^
/opt/local/include/Poco/Net/DatagramSocket.h:35:2: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
        DatagramSocket();
        ^
/opt/local/include/Poco/Net/DatagramSocket.h:51:2: note: candidate constructor not viable: requires at least 2 arguments, but 1 was provided
        DatagramSocket(const SocketAddress& address, bool reuseAddress, bool reusePort = false, bool ipV6Only = false);
        ^
```

**Comment by ncorgan** [comment]
I'll take a look at this in the next few days.
